---

- name: set up IAM profile statements
  set_fact:
    iam_profiles: []
    iam_arn_whitelist_list: "{{ iam_arn_whitelist }}"

- name: set up IAM profile statements
  set_fact:
    iam_profiles: "{{ iam_profiles }} + [ { 'Action': 'es:*', 'Effect': 'Allow', 'Principal': { 'AWS': ['{{ item }}'] } } ]"
  with_items: "{{ iam_arn_whitelist }}"
  when: "{{ iam_arn_whitelist_list|length > 0 }}"

- name: set up es_access_policy with IAM profiles
  set_fact:
    es_access_policy:
      Version: '2012-10-17'
      Statement: "{{ iam_profiles }} + [ { 'Action': 'es:*', 'Principal': '*', 'Effect': 'Allow', 'Condition': { 'IpAddress': { 'aws:SourceIp': {{ es_ip_whitelist }} } } } ]"
  when:
    - "{{ iam_profiles|length > 0 }}"

- name: set up es_access_policy without IAM profiles
  set_fact:
    es_access_policy:
      Version: '2012-10-17'
      Statement:
        - Action: 'es:*'
          Principal: '*'
          Effect: Allow
          Condition:
            IpAddress:
              'aws:SourceIp': "{{ es_ip_whitelist }}"
  when:
   - es_access_policy

- name: set up es_cluster_config and es_ebs_config for public endpoint
  set_fact:
    es_cluster_config:
      InstanceType: "{{ es_instance_type }}"
      InstanceCount: "{{ es_instance_count | int }}"
      DedicatedMasterEnabled: "{{ es_dedicated_master | bool }}"
      ZoneAwarenessEnabled: "{{ es_zone_awareness | bool }}"
    es_ebs_config:
      EBSEnabled: "{{ es_ebs_enabled | bool }}"
  when:  es_subnets is undefined

- name: set up vpc config variables
  set_fact:
    es_vpc_config:
      SubnetIds: "{{ es_subnets }}"
      SecurityGroupIds: "{{ es_security_groups }}"
    es_cluster_config:
      InstanceType: "{{ es_instance_type }}"
      InstanceCount: "{{ es_instance_count | int }}"
      DedicatedMasterEnabled: "{{ es_dedicated_master | bool }}"
      ZoneAwarenessEnabled: true
    es_ebs_config:
      EBSEnabled: "{{ es_ebs_enabled | bool }}"
  when:
    - es_subnets

- name: set master configs
  set_fact:
    es_cluster_config: "{{ es_cluster_config | combine( {
      'DedicatedMasterType': es_dedicated_master_type,
      'DedicatedMasterCount': es_dedicated_master_count
    }) }}"
  when: es_dedicated_master | bool

- name: set ebs configs when enabled
  set_fact:
    es_ebs_config: "{{ es_ebs_config | combine( {
      'VolumeType': es_ebs_volume_type,
      'VolumeSize': es_ebs_volume_size
    } ) }}"
  when: es_ebs_enabled | bool

- name: set iops for io1 volumes
  set_fact:
    es_ebs_config: "{{ es_ebs_config | combine( { 'Iops' : es_ebs_iops } ) }}"
  when: es_ebs_volume_type == 'io1'

- block:
    - debug: var=es_cluster_config
    - debug: var=es_access_policy
    - debug: var=es_ebs_config
  when: es_debug | bool
