---

- name: get list of Elasticsearch domains
  command: aws --region "{{ aws_region }}" es list-domain-names
  register: es_domains_output
  # when: not es_domains_output

- name: extract json
  set_fact:
    es_domains: "{{ (es_domains_output.stdout | from_json)
                    | json_query('DomainNames[*].DomainName')
                    | list }}"

# TODO: remove
- debug: var=es_domains
  when: "'fiance-staging' in es_domains"
