---

- name: get list of Elasticsearch domains
  command: aws --region "{{ aws_region }}" es list-domain-names
  register: es_domains_output
  # when: not es_domains_output

- name: extract json
  set_fact:
    es_domains: "{{ (es_domains_output.stdout | from_json)
                    | json_query('DomainNames[*].DomainName')
                    | list }}"


- name: determine if Elasticsearch domain already exists
  set_fact:
    es_domain_exists: yes
  when: es_domain_name in es_domains

- block:
    - debug: var=es_domains
    - debug: var=es_domain_exists
  when: es_debug | bool
